name: l2geth lint and build

on:
  pull_request:
    branches:
      - 'debank'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./l2geth

env:
  REGISTRY: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com
  IMAGE: op-l2geth
  DOCKERFILE: Dockerfile

jobs:
  lint:
    runs-on: [self-hosted, general]

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

          #- name: Lint
          #run: |
          #make lint

  build:
    runs-on: [self-hosted, general]

    needs: lint

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set env
      run: |
        # echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "REVISION=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Docker build and push
      run: |
        docker build -t ${REGISTRY}/${IMAGE}:${REVISION} -f ${DOCKERFILE} ..
        docker push ${REGISTRY}/${IMAGE}:${REVISION}
        docker run --name dryrun --rm ${REGISTRY}/${IMAGE}:${REVISION} version
        docker rmi ${REGISTRY}/${IMAGE}:${REVISION}

    - name: Lark Notification
      continue-on-error: true
      run: |
        notiv3 "Blockchain Optimism latest image pushed 🎉" ${REGISTRY}/${IMAGE}:${REVISION}
